version: "3.8"

networks:
  custom:
    driver: bridge

services:
  # Node
  # node:
  #   image: node:18
  #   container_name: node_chat
  #   tty: true
  #   working_dir: /var/www/html
  #   ports:
  #     - "4000:4000"
  #     - "5173:5173"
  #   volumes:
  #     - .:/var/www/html
  #   networks:
  #     - custom

  # #Mongo
  # mongo:
  #   image: mongo:latest
  #   container_name: mongo_chat
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./docker/mongo/db:/data/db
  #     - ./docker/mongo/log:/var/log/mongodb
  #   networks:
  #     - custom

  #Postgres
  postgres:
    image: postgres:14-alpine
    container_name: postgres_chat
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=chat
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/lib:/var/lib/postgresql/data
    networks:
      - custom

  adminer:
    image: adminer:latest
    container_name: adminer_chat
    ports:
      - "8080:8080"
    networks:
      - custom

  redis:
    image: redis/redis-stack:latest
    container_name: redis_chat
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - custom

  #Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - custom
  #Kafka
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - custom
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    restart: always
    ports:
      - "8090:8080"
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - custom
